# Dockerc compose only for developing purpose

version: "3.8"

services:
  couchdb:
    build:
      context: ./couchdb
      dockerfile: Dockerfile
    container_name: hr_couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password

  dbinit:
    image: curlimages/curl
    command: >
      sh -c
      "sleep 5s &&
      curl -X PUT http://admin:password@couchdb:5984/_global_changes &&
      sleep 1s &&
      curl -X PUT http://admin:password@couchdb:5984/_users/_security -d '{}' &&
      sleep 1s &&
      curl -X PUT http://admin:password@couchdb:5984/hospitalrun?partitioned=false &&
      sleep 1s &&
      curl -X PUT http://admin:password@couchdb:5984/_users/org.couchdb.user:username -H "Accept: application/json" -H "Content-Type: application/json" -d '{"name": "username", "password": "password", "metadata": { "givenName": "John", "familyName": "Doe"}, "roles": [], "type": "user"}'
      && sleep 1s
      "
