name: GitHub CI

on: [push, pull_request]

jobs:
  npm:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x, 13.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # exclude:
        #   - os: windows-latest
        #     node-version: 13.x
    steps:
      - run: git config --global core.autocrlf false # this is needed to prevent git changing EOL after cloning on Windows OS
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install with npm
        run: |
          npm install
      - name: Lint code
        run: |
          npm run lint
      - name: Build
        if: always()
        run: |
          npm run build
      - name: Run tests
        if: always()
        run: |
          npm run coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info

  yarn:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x, 13.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # exclude:
        #   - os: windows-latest
        #     node-version: 13.x
    steps:
      - run: git config --global core.autocrlf false # this is needed to prevent git changing EOL after cloning on Windows OS
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Init yarn
        run: |
          npm install -g yarn
      - name: Install with yarn
        run: |
          yarn install
      - name: Lint code
        run: |
          yarn lint
      - name: Build
        run: |
          yarn build
      - name: Run tests
        run: |
          yarn test:ci
